# Generated by Django 5.1.5 on 2025-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='jins',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10),
        ),
    ]
